version: '3.7'

services:
  postgres:
    image: postgres:15.6
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rating_network

  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"
    networks:
      - rating_network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

networks:
  rating_network:
    driver: bridge

volumes:
  postgres_data:
